name: ci

on: push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Baixar o repositório
              uses: actions/checkout@v4

            - name: Instalar o Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11.5

            - name: Instalar dependências
              run:  pip install -r requirements.txt

            - name: Rodar minha rotina de testes
              run:  run pytest tests -v